# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapShotSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapShotSample

  target 'SnapShotSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapShotSampleUITests' do
    # Pods for testing
  end

end
